
    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP136', 'ARCK BANI GUPTA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP137', 'KHUSHAL RASTI SHROFF', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP138', 'ARYAN AMEET GUPTA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP140', 'TANISH TARAK KINKHABWALA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP141', 'PATEL MIRAL DHANSUKHBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP142', 'PATEL RUDRA PRITESH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP143', 'KANSARA MUKUND RAJESH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP144', 'MEHTA PRATHAM VINAYKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP145', 'MEHTA RISHI DHARMESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP146', 'HEMANG NAVHAL', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP147', 'SONPAL KRISH MANISH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP148', 'MALI JAIMIN JITENDRA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP149', 'TRIVEDI KAVAN MEHULBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP150', 'TWINKAL AJMERA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP151', 'PATEL AYUSH DILIPKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP152', 'SOLANKI AKSHADIPSINH YOGARAJSINH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP153', 'VEDESH SATYEN PANDYA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP154', 'SHETH HIT TEJALKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP155', 'SONI PIYUSH ASHVINKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP156', 'PATEL SHLOK TUSHAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP158', 'PATEL HAMMESH ANILBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP160', 'SUDHEER PANDEY', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP161', 'DEVANI AYUSH ASHVINBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP162', 'PARV DESAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP163', 'SAMANT RITESH RATHOD', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP164', 'DEEP GIRISHBHAI PATOLIYA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP165', 'GAURAV BISHNOI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP166', 'PATEL PARAM VIRALKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP167', 'HARICHAND LONIYA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP168', 'PATEL MOKSH RAJESHBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP170', 'JEET ZALA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP171', 'VYAS MEET RUSHINKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP172', 'GANDHI RAJ HITESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP174', 'ANSH SONI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP176', 'BAGRECHA PEHEL', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP177', 'HRITIK JAYESH MAKWANA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP178', 'MAHEK KAMOL', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP179', 'TAILOR SUJAL DHARMESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP180', 'DHYANI KOKIL DAVE', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP181', 'MAITREE KALPESH MISTRY', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP182', 'GADHIYA CHETAN BHAVESHBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP183', 'AGRAWAL RUCHIT RAKESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP184', 'DIYA ROKADIA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP186', 'PANTH PATEL', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP187', 'PATEL MIT SONESHBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP188', 'MODI HEM BHARATBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP190', 'PATEL KAIVAL MAHENDRAKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP191', 'BIKENDRA LOHAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP192', 'CHAUHAN HET RAJESH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP193', 'JAIN VANSH HANSRAJ', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP194', 'RAVI HARSHAL BHATT', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP195', 'PATEL KALP CHETANKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP197', 'PATEL NAITIKKUMAR JAGDISHBHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP198', 'MEHTA KRISH NILESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP199', 'PRAJAPATI VRAJKUMAR JITENDRABHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP200', 'MALAV MEVADA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP201', 'DILIP KOHAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP202', 'PRINCE RAKESHKUMAR KOLADIYA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP203', 'PATEL PRIYANK DHARMENDRABHAI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP204', 'MEHTA KRISHNA NILESHKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP514D', 'TRESHA BHALAVAT', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP515D', 'VIDHYANI GANDHI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP516D', 'VRAJ PATEL', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP517D', 'JENISH TANK', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP518D', 'MIHIR R. GOSWAMI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP519D', 'RATHOD DHVANIT NIXANKUMAR', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G5');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP520D', 'GABANI RAHI', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP521D', 'MEETRAJSINH JADEJA', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP522D', 'HRIDAY JAIN', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    

    INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, STUDENT_TYPE, IMAGE_PATH, DIVISION_ID, GROUP_ID)
    VALUES ('23BCP523D', 'PUSHTI JIGNESHBHAI SHAH', NULL, NULL, 'CSE', 'SoT', 'BTECH_CSE', 'Domestic', NULL, 'D3', 'G6');
    