-- Assumed Values:
-- DEPT_CODE: 'ME'
-- SCHOOL_ID: 'SoT'
-- PROGRAM_ID: 'BTECH_ME'
-- CONTACT_NO: NULL
-- STUDENT_TYPE: 'Domestic'
-- IMAGE_PATH: NULL
-- EMAIL: [Final Roll No.]@pdpu.ac.in
-- DIVISION_ID Mapping: 'Div-1' -> 'D1_ME', 'Div-2' -> 'D2_ME'
-- GROUP_ID Mapping: 'A1'/'A2'/'A3'/'A4' directly from PDF

-- Students 1-34 (Division D1_ME, Group A1)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BME001', 'Piyush Singh Rajput', NULL, '23BME001@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME002', 'Pal Thakor', NULL, '23BME002@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME003', 'Ansh Rajput', NULL, '23BME003@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME004', 'Manav Atul Hingrajia', NULL, '23BME004@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME005', 'Harshvardhan Kaushal Shah', NULL, '23BME005@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME006', 'Jay Gopal Vachheta', NULL, '23BME006@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME007', 'Meet V Kachhadiya', NULL, '23BME007@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME008', 'Tirth Ghemarbhai Desai', NULL, '23BME008@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME009', 'Smit Dadhaniya', NULL, '23BME009@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME010', 'Tanay Chetan Mehta', NULL, '23BME010@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME011', 'Yash Pitroda', NULL, '23BME011@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME012', 'Rudra Patel', NULL, '23BME012@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME013', 'Rusheel Rahul Amin', NULL, '23BME013@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME014', 'Mohammed Bilal Kutbuddin Shaikh', NULL, '23BME014@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME015', 'Patel Rushi Sanjaykumar', NULL, '23BME015@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME016', 'Nachupatel', NULL, '23BME016@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME017', 'Vikrant Bangale', NULL, '23BME017@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME018', 'Setu Priyesh Desai', NULL, '23BME018@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME019', 'Gohil Mihir Gautambahi', NULL, '23BME019@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME020', 'Piyeja Chirag Harshadbhai', NULL, '23BME020@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME021', 'Rasesh Jayakanth Nair', NULL, '23BME021@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME022', 'Chaitanya Harekrushna Bhutwala', NULL, '23BME022@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME023', 'Tanay Parikh', NULL, '23BME023@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME024', 'Roshan Sahu', NULL, '23BME024@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME025', 'Krushant Mansukh Kayadra', NULL, '23BME025@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME026', 'Chaudhary Pritesh Gagdasbhai', NULL, '23BME026@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME027', 'Darshil Nimeshkumar Shah', NULL, '23BME027@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME028', 'Prekshivika', NULL, '23BME028@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME029', 'Jenil', NULL, '23BME029@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME030', 'Dharmil Patel', NULL, '23BME030@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME031', 'Somin Divyesh Kachhi', NULL, '23BME031@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME032', 'Sagar Pujara', NULL, '23BME032@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME033', 'Jesalrajsinh Jadeja', NULL, '23BME033@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL),
('23BME034', 'Yug Yogesh Bhai Kikani', NULL, '23BME034@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A1', 'Domestic', NULL);

-- Students 35-68 (Division D1_ME, Group A2)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BME035', 'Rishabh Badgujar', NULL, '23BME035@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME036', 'Khwahish Munjal Patel', NULL, '23BME036@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME037', 'Samarth Rajeshkumar Patel', NULL, '23BME037@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME038', 'Harsh Jigarkumar Patel', NULL, '23BME038@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME039', 'Parmar Rahulkumar Hirabhai', NULL, '23BME039@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME040', 'Kedar Manthan Rawal', NULL, '23BME040@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME041', 'Dirgh Kaushalbhai Mehta', NULL, '23BME041@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME042', 'Yashkumar Sunilb Panchal', NULL, '23BME042@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME043', 'Shreya Samir Patel', NULL, '23BME043@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME044', 'Shlok Vaidya', NULL, '23BME044@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME045', 'Yash Vitthal Rathod', NULL, '23BME045@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME046', 'Manan Changela', NULL, '23BME046@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME047', 'Ansh Patel', NULL, '23BME047@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME048', 'Patel Om Pareshkumar', NULL, '23BME048@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME049', 'Ronit Chakraborty', NULL, '23BME049@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME050', 'Priyansh Panchal', NULL, '23BME050@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME051', 'Dev Jigneshbhai Kadiya', NULL, '23BME051@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME052', 'Meghaviba Vaghela', NULL, '23BME052@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME053', 'Manav Pragnesh Jadeja', NULL, '23BME053@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME054', 'Sherwin Saju Abraham', NULL, '23BME054@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME055', 'Krishil Hardikkumar Chokshi', NULL, '23BME055@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME056', 'Parv Hasmukhbhai Patel', NULL, '23BME056@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME057', 'Maharshi Ashish Manvar', NULL, '23BME057@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME058', 'Makwana Sujalkumar Dineshbhai', NULL, '23BME058@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME059', 'Hariom Balraj Dabhi', NULL, '23BME059@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME060', 'Pranay Bharadwaj', NULL, '23BME060@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME061', 'Neelay Jain', NULL, '23BME061@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME062', 'Devarsh Girish Banker', NULL, '23BME062@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME063', 'Prayag Ashok Patel', NULL, '23BME063@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME064', 'Shubham Sharma', NULL, '23BME064@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME065', 'Tirth Sheth', NULL, '23BME065@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME066', 'Kushagra Verma', NULL, '23BME066@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME067', 'Kathankumar', NULL, '23BME067@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL),
('23BME068', 'Rudra Chaudhari', NULL, '23BME068@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D1_ME', 'A2', 'Domestic', NULL);

-- Students 69-102 (Division D2_ME, Group A3)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BME069', 'Jeet Gaurang Shukla', NULL, '23BME069@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME070', 'Om Tiwari', NULL, '23BME070@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME071', 'Harsh Harichandra Luhar', NULL, '23BME071@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME072', 'Yuvraj Singh Adhana', NULL, '23BME072@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME073', 'Divam Patel', NULL, '23BME073@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME074', 'Divy Hiteshbhai Kakadiya', NULL, '23BME074@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME075', 'Doshi Chaitya Ashish', NULL, '23BME075@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME076', 'Vaishali Vinay Sharma', NULL, '23BME076@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME077', 'Vraj Prashant Parikh', NULL, '23BME077@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME078', 'Patel Maharshi Piyushbhai', NULL, '23BME078@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME079', 'Mohnish J Pathak', NULL, '23BME079@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME080', 'Harshita Harichandra Luhar', NULL, '23BME080@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME081', 'Pateliya Dev Dilipbhai', NULL, '23BME081@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME082', 'Daksh Gor', NULL, '23BME082@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME083', 'Het Nileshchandra Dhruv', NULL, '23BME083@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME084', 'Krish Kirit Lad', NULL, '23BME084@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME085', 'Tirth Ileshkumar Patel', NULL, '23BME085@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME086', 'Chinmay Bhushan Shah', NULL, '23BME086@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME087', 'Dhairya Himanshu Shah', NULL, '23BME087@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME088', 'Vaibhav Chhablani', NULL, '23BME088@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME089', 'Patel Jaykumar Rajendrabhai', NULL, '23BME089@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME090', 'Dishant Pragnesh Khokhari', NULL, '23BME090@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME091', 'Kavya Badal Dalal', NULL, '23BME091@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME092', 'Amrutiya Darshit', NULL, '23BME092@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME093', 'Arjun Ajay Prajapati', NULL, '23BME093@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME094', 'Ansh', NULL, '23BME094@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME095', 'Surbhi Rathi', NULL, '23BME095@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME096', 'Tanmay Sunilkumar Gupta', NULL, '23BME096@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME097', 'Het Narodia', NULL, '23BME097@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME098', 'Aditya Singh', NULL, '23BME098@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME099', 'Ayush Singh', NULL, '23BME099@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME100', 'Yash Ishwarlal Shah', NULL, '23BME100@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME101', 'Siddhant Chudasama', NULL, '23BME101@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL),
('23BME102', 'Ishan Ashvinbhai Khoont', NULL, '23BME102@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A3', 'Domestic', NULL);

-- Students 103-136 (Division D2_ME, Group A4)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BME103', 'Harshil Sanjay Shete', NULL, '23BME103@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME104', 'Anshul', NULL, '23BME104@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME105', 'Suthar Jainil Himanshu', NULL, '23BME105@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME106', 'Aarav Chirag Patel', NULL, '23BME106@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME107', 'Ashwin Vishal', NULL, '23BME107@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME108', 'Patel Parth Amitkumar', NULL, '23BME108@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME109', 'Rishabh Thomre', NULL, '23BME109@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME110', 'Jay Keyur Vakharia', NULL, '23BME110@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME111', 'Preet Amish Champaneria', NULL, '23BME111@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME112', 'Yash Mastry', NULL, '23BME112@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME113', 'Gandhi Nirmal Gopalbhai', NULL, '23BME113@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME114', 'Arjun Keshav', NULL, '23BME114@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME115', 'Ujjwal Soni', NULL, '23BME115@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME116', 'Prithvi Mihirsinh Chauhan', NULL, '23BME116@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME117', 'Aditya Devang Shah', NULL, '23BME117@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME118', 'Vishvesh Sanjaybhai Prajapati', NULL, '23BME118@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME119', 'Parit Hardik Parekh', NULL, '23BME119@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME120', 'Varun Sandeep Vyas', NULL, '23BME120@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME121', 'Patel Tirthkumar', NULL, '23BME121@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME122', 'Jay Anand Thakkar', NULL, '23BME122@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME123', 'Patel Krish Bipinkumar', NULL, '23BME123@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME124', 'Darshkumar Dobariya', NULL, '23BME124@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME125', 'Mohak Rishiraj Trivedi', NULL, '23BME125@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME126', 'Vansh Panchal', NULL, '23BME126@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME127', 'Patel Dev Rasikbhai', NULL, '23BME127@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME128', 'Umang Joshi', NULL, '23BME128@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME129', 'Devarsh Shashikant Hirvaniya', NULL, '23BME129@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME130', 'Aaditya Jaykumar Pandya', NULL, '23BME130@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME131', 'Priaan Vijay Pancholi', NULL, '23BME131@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME132', 'Soham Dhiren Parmar', NULL, '23BME132@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME133', 'Mahir Jatinkumar Patel', NULL, '23BME133@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME134', 'Vyom Bakulesh Vadgama', NULL, '23BME134@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL),
('23BME135', 'Isaias Maifa Junior', NULL, '23BME135@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL), -- International?
('22BME025', 'Shrey Avinashi', NULL, '22BME025@pdpu.ac.in', 'ME', 'SoT', 'BTECH_ME', 'D2_ME', 'A4', 'Domestic', NULL); -- Note older Roll No