-- Updated Assumed Values:
-- DEPT_CODE: 'ICT'
-- SCHOOL_ID: 'SoT'  <-- Changed
-- PROGRAM_ID: 'BTECH_ICT' <-- Changed
-- CONTACT_NO: NULL
-- STUDENT_TYPE: 'Domestic'
-- IMAGE_PATH: NULL
-- EMAIL: [Final Roll No.]@pdpu.ac.in
-- DIVISION_ID Mapping: 'Div-1' -> 'D1', 'Div-2' -> 'D2', 'Div-3' -> 'D3'
-- GROUP_ID Mapping: 'H1' -> 'H1', 'H2' -> 'H2', ... 'H6' -> 'H6'

-- Students 1-44 (Division D1, Group H1)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT001', 'Utsav Subhashbhai Vadaliya', NULL, '23BIT001@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT002', 'Prince Kartikbhai Patoliya', NULL, '23BIT002@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT003', 'Jayesh Gautam', NULL, '23BIT003@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT004', 'Yashviben Jiteshkumar Shah', NULL, '23BIT004@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT005', 'Shrey Himanshu Patel', NULL, '23BIT005@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT006', 'Gul Nilesh Batra', NULL, '23BIT006@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT007', 'Darshna Sanjaybhai Ajudia', NULL, '23BIT007@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT008', 'Deep Piyushbhai Shingala', NULL, '23BIT008@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT009', 'Parth Panot', NULL, '23BIT009@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT010', 'Chandrak', NULL, '23BIT010@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT011', 'Patel Shruti Ketanbhai', NULL, '23BIT011@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT012', 'Vaibhav Pachori', NULL, '23BIT012@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT013', 'Hirapara Deep', NULL, '23BIT013@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT014', 'Om Rajkumar Ahuja', NULL, '23BIT014@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT015', 'Dhupkumar Rajeshbhai Thumbadiya', NULL, '23BIT015@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT016', 'Vanara Aditi Hiteshbhai', NULL, '23BIT016@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT017', 'Aidasani Vishal Devkumar', NULL, '23BIT017@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT018', 'Pallavi Ashvinbhai Pansuriya', NULL, '23BIT018@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT019', 'Aryan Mineshkumar Suthar', NULL, '23BIT019@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT020', 'Krunal Rajeshbhai Makwana', NULL, '23BIT020@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT021', 'Ishaan Jaydeep Gor', NULL, '23BIT021@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT022', 'Maurya Samir Patel', NULL, '23BIT022@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT023', 'Jeel Ashwinbhai Aghera', NULL, '23BIT023@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT024', 'Dharman Patel', NULL, '23BIT024@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT025', 'Devam Chiragkumar Gor', NULL, '23BIT025@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT026', 'Krutarth Upendrakumar Joshi', NULL, '23BIT026@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT027', 'Namya Janmay Shah', NULL, '23BIT027@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT028', 'Darshil Tusharbhai Doshi', NULL, '23BIT028@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT029', 'Krish Patel', NULL, '23BIT029@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT030', 'Shivam Kumar', NULL, '23BIT030@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT031', 'Ananya Sharma', NULL, '23BIT031@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT032', 'Rudra Bimal Patel', NULL, '23BIT032@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT033', 'Jash Nandish Parekh', NULL, '23BIT033@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT034', 'Lakshya Sunil Saraf', NULL, '23BIT034@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT035', 'Jaineel Roshan Hemnani', NULL, '23BIT035@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT036', 'Anushree Lodha', NULL, '23BIT036@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT037', 'Shlok Ashish Patel', NULL, '23BIT037@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT038', 'Mit Ketanbhai Darji', NULL, '23BIT038@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT039', 'Chaudhary Chiragkumar Virsangbhai', NULL, '23BIT039@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT040', 'Patel Vraj Shaileshbhai', NULL, '23BIT040@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT041', 'Prajapati Bhargav Kamleshbhai', NULL, '23BIT041@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT042', 'Jishnu Bhargavbhai Thacker', NULL, '23BIT042@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT043', 'Chirag Buliya', NULL, '23BIT043@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL),
('23BIT044', 'Rikin Jayeshkumar Parekh', NULL, '23BIT044@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H1', 'Domestic', NULL);

-- Students 45-87 (Division D1, Group H2)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT045', 'Ridham Harshadkumar Patel', NULL, '23BIT045@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT046', 'Tejas Lokesh Arekar', NULL, '23BIT046@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT047', 'Kaushal', NULL, '23BIT047@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT048', 'Hemaksh Dharmesh Soni', NULL, '23BIT048@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT049', 'Nupur Paliwal', NULL, '23BIT049@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT050', 'Harshit Daxini', NULL, '23BIT050@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT051', 'Chaudhari Dixit', NULL, '23BIT051@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT052', 'Deep Sherathiya', NULL, '23BIT052@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT053', 'Het Pratikbhai Sanghvi', NULL, '23BIT053@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT054', 'Rishabh Nandekar', NULL, '23BIT054@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT055', 'Dhyeya Nilay Choksi', NULL, '23BIT055@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT056', 'Parv Sachin Naik', NULL, '23BIT056@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT057', 'Tejas Aishwarya Singh', NULL, '23BIT057@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT058', 'Jash Dhirajlal Dhokiya', NULL, '23BIT058@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT059', 'Patel Om Gautambhai', NULL, '23BIT059@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT060', 'Jenil Jiteshkumar Savaliya', NULL, '23BIT060@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT061', 'Nitya Mayur Modi', NULL, '23BIT061@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT062', 'Tanay Rikeshbhai Shah', NULL, '23BIT062@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT063', 'Desai Krisha Rajanikant', NULL, '23BIT063@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT064', 'Darshan Bhagvanbhai Prajapati', NULL, '23BIT064@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT065', 'Yakeen Jain', NULL, '23BIT065@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT066', 'Pal Kamleshbhai Patel', NULL, '23BIT066@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT067', 'Kavisha Sharma', NULL, '23BIT067@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT068', 'Tejas Bhaveshkumar Patel', NULL, '23BIT068@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT069', 'Abhishek Manish Gupte', NULL, '23BIT069@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT070', 'Dhruvkumar Jegoda', NULL, '23BIT070@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT071', 'Jaydeep Bhagvat', NULL, '23BIT071@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT072', 'Nisarg Shailesh Sahayata', NULL, '23BIT072@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT073', 'Raghav Kumar', NULL, '23BIT073@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT074', 'Babariya Monil Jivanbhai', NULL, '23BIT074@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT075', 'Heer Monpara', NULL, '23BIT075@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT076', 'Vala Rishabh Hareshkumar', NULL, '23BIT076@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT077', 'Gondaliya Harshal Chimanbhai', NULL, '23BIT077@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT078', 'Dev Gami', NULL, '23BIT078@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT079', 'Jyotikar Dhruv', NULL, '23BIT079@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT080', 'Rana Om Atulbhai', NULL, '23BIT080@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT081', 'Arya Amul Dedhiya', NULL, '23BIT081@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT082', 'Prasham Ketankumar Patel', NULL, '23BIT082@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT083', 'Manas Jha', NULL, '23BIT083@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT084', 'Priyansh K Raval', NULL, '23BIT084@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT085', 'Dhyey', NULL, '23BIT085@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT086', 'Dax Vishnubhai Thakkar', NULL, '23BIT086@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL),
('23BIT087', 'Parth Rajendra Bhatt', NULL, '23BIT087@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D1_ICT', 'H2', 'Domestic', NULL);

-- Students 88-130 (Division D2, Group H3)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT088', 'Birva Jatin Khakhi', NULL, '23BIT088@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT089', 'Gupta Vinit Kumar', NULL, '23BIT089@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT090', 'Jinam Sanghvi', NULL, '23BIT090@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT091', 'Devansh Rakeshbhai Patel', NULL, '23BIT091@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT092', 'Hil Bharatbhai Kalathiya', NULL, '23BIT092@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT093', 'Jay Anilkumar Senjaria', NULL, '23BIT093@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT094', 'Rudra Bharatbhai Patel', NULL, '23BIT094@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT095', 'Aastha Hotwani', NULL, '23BIT095@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT096', 'Divy Sanjaykumar Patel', NULL, '23BIT096@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT097', 'Saumya Kartik Joshi', NULL, '23BIT097@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT098', 'Sunidhi Ticroliya', NULL, '23BIT098@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT099', 'Dhruvsingh Pravinsingh Rajpurohit', NULL, '23BIT099@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT100', 'Divija Abhay Kavishvar', NULL, '23BIT100@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT101', 'Ayaz Deraiya', NULL, '23BIT101@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT102', 'Kaushik Parmar', NULL, '23BIT102@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT103', 'Patel Swayam Pravinbhai', NULL, '23BIT103@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT104', 'Rajesh Chaudhary', NULL, '23BIT104@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT105', 'Meghav Maulik Vora', NULL, '23BIT105@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT106', 'Jay Mukesh Vaghela', NULL, '23BIT106@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT107', 'Raj Manishkumar Patel', NULL, '23BIT107@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT108', 'Grishma Makwana', NULL, '23BIT108@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT109', 'Krushang Dahyabhai Makwana', NULL, '23BIT109@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT110', 'Prem Saraswat', NULL, '23BIT110@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT111', 'Aditya Sikdar', NULL, '23BIT111@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT112', 'Khushi Hansrajbhai Panchotiya', NULL, '23BIT112@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT113', 'Yash Rajeshbhai Gamit', NULL, '23BIT113@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT114', 'Shah Akhil Dhaval', NULL, '23BIT114@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT115', 'Diya Khamar', NULL, '23BIT115@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT116', 'Labhesh Shrimali', NULL, '23BIT116@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT117', 'Vatsal Sanjaykumar Patel', NULL, '23BIT117@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT118', 'Nehanshu K. Rathod', NULL, '23BIT118@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT119', 'Prerita Darshan Shukla', NULL, '23BIT119@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT120', 'Parth Thakkar', NULL, '23BIT120@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT121', 'Hardi', NULL, '23BIT121@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT122', 'Shavya Nitesh Solanki', NULL, '23BIT122@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT123', 'Saumya Babariya', NULL, '23BIT123@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT124', 'Dev Patel', NULL, '23BIT124@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT125', 'Jash Mahesh Vaishnhav', NULL, '23BIT125@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT126', 'Fenil Girishbhai Kaneria', NULL, '23BIT126@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT127', 'Parthkumar Nareshbhai Patel', NULL, '23BIT127@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT128', 'Sahaj Ghanshyambhai Saliya', NULL, '23BIT128@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT129', 'Rudra Desai', NULL, '23BIT129@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL),
('23BIT130', 'Ayush Adroja', NULL, '23BIT130@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H3', 'Domestic', NULL);

-- Students 131-173 (Division D2_ICT, Group H4)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT131', 'Jyot Gautambhai Raval', NULL, '23BIT131@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT132', 'Lunechiya Dhyan Dineshbhai', NULL, '23BIT132@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT133', 'Parmar Jaydeep Kailashbhai', NULL, '23BIT133@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT134', 'Purvansh Tushar Dave', NULL, '23BIT134@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT135', 'Mukundwa Uwase Aristide', NULL, '23BIT135@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT136', 'Johnsy Asari', NULL, '23BIT136@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT137', 'Krish Sanjay Macwan', NULL, '23BIT137@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT138', 'Namya Vimalkumar Patel', NULL, '23BIT138@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT139', 'Vishvavaland', NULL, '23BIT139@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT140', 'Hemang. Shreemali', NULL, '23BIT140@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT141', 'Mihir Chandrakant Aadki', NULL, '23BIT141@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT142', 'Sachi Nitesh Shah', NULL, '23BIT142@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT143', 'Tadvi Yatharth Mahendrakumar', NULL, '23BIT143@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT144', 'Anish Dharmendrabhai Patel', NULL, '23BIT144@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT145', 'Dev H Mehta', NULL, '23BIT145@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT146', 'Aneree Maulikkumar Patel', NULL, '23BIT146@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT147', 'Manav Chaudhari', NULL, '23BIT147@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT148', 'Anirudhha Swaroop Dalal', NULL, '23BIT148@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT149', 'Yug Rajeshkumar Thakkar', NULL, '23BIT149@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT150', 'Sambhav Heda', NULL, '23BIT150@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT151', 'Shriya Rahul Choksi', NULL, '23BIT151@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT152', 'Vishwajeetsinh Siddharth Khuman', NULL, '23BIT152@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT153', 'Pushkar Pareshbhai Kanjani', NULL, '23BIT153@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT154', 'Rajvi Goyani', NULL, '23BIT154@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT155', 'Niva Chirag Desai', NULL, '23BIT155@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT156', 'Jeet Patel', NULL, '23BIT156@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT157', 'Patel Virat Jaydeep', NULL, '23BIT157@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT158', 'Tapan Alpeshkumar Patel', NULL, '23BIT158@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT159', 'Himani Manishkumar Patel', NULL, '23BIT159@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT160', 'Smit Patel', NULL, '23BIT160@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT161', 'Pulin Dhirendra Rai', NULL, '23BIT161@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT162', 'Moksh Bhavesh Parekh', NULL, '23BIT162@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT163', 'Patel Prem Sandeepkumar', NULL, '23BIT163@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT164', 'Soham Chetanbhai Gor', NULL, '23BIT164@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT165', 'Hozefa Ilyas Travadi', NULL, '23BIT165@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT166', 'Basundhara Bera', NULL, '23BIT166@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT167', 'Shaarav Vaibhav Gore', NULL, '23BIT167@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT168', 'Harsh Ashokkumar Varia', NULL, '23BIT168@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT169', 'Prince Panchal', NULL, '23BIT169@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT170', 'Vyas Vedant Parikshit', NULL, '23BIT170@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT171', 'Yesha Dharvadia', NULL, '23BIT171@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT172', 'Vaghela Meetraj Dharmendrasinh', NULL, '23BIT172@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL),
('23BIT173', 'Vraj Rajesh Hirani', NULL, '23BIT173@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D2_ICT', 'H4', 'Domestic', NULL);

-- Students 174-216 (Division D3, Group H5)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT174', 'Jainee', NULL, '23BIT174@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT175', 'Prashu Singhal', NULL, '23BIT175@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT176', 'Rahul Kumar', NULL, '23BIT176@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT177', 'Aman Amrutbhai Tabiyar', NULL, '23BIT177@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT178', 'Patel Antara Kalpesh', NULL, '23BIT178@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT179', 'Manav Jaiminkumar Patel', NULL, '23BIT179@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT180', 'Krishna Sanjaybhai Khernar', NULL, '23BIT180@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT181', 'Jaimin Bhaveshkumar Bhatt', NULL, '23BIT181@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT182', 'Rakshit Jain', NULL, '23BIT182@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT183', 'Suhagiya Chetankumar Prafullbhai', NULL, '23BIT183@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT184', 'Jinil Vikashbhai Patel', NULL, '23BIT184@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT185', 'Mahitosh Niravbhai Desai', NULL, '23BIT185@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT186', 'Maanav Sanjaybhai Dhorajiya', NULL, '23BIT186@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT187', 'Yashita Brijesh Loya', NULL, '23BIT187@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT188', 'Diyora Tanisha', NULL, '23BIT188@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT189', 'Ayushi Chiragkumar Maniar', NULL, '23BIT189@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT190', 'Patel Milav Kamleshkumar', NULL, '23BIT190@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT191', 'Naitik Bharatbhai Jadav', NULL, '23BIT191@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT192', 'Chirag V Maloo', NULL, '23BIT192@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT193', 'Mali Sumit Mahendrakumar', NULL, '23BIT193@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT194', 'Jwanil Suketu Modi', NULL, '23BIT194@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT195', 'Jay Yatin Dave', NULL, '23BIT195@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT196', 'Dudhat Dharmik Vrajlal', NULL, '23BIT196@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT197', 'Parmar Ansh Dipeshkumar', NULL, '23BIT197@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT198', 'Neel Pankajbhai Italiya', NULL, '23BIT198@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT199', 'Bhumik Verma', NULL, '23BIT199@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT200', 'Nidhi Pujara', NULL, '23BIT200@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT201', 'Prasham Dipenbhai Doshi', NULL, '23BIT201@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT202', 'Aditya Ajaykumar Pandya', NULL, '23BIT202@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT203', 'Rabadiya Sanket Pravinbhai', NULL, '23BIT203@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT204', 'Gnyani', NULL, '23BIT204@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT205', 'Devesh Naresh Wadhwani', NULL, '23BIT205@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT206', 'Krishna Pathak', NULL, '23BIT206@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT207', 'Vanshil Suresh Patel', NULL, '23BIT207@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT208', 'Zala Mayank Jaydipsinh', NULL, '23BIT208@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT209', 'Sutariya Vedant Jamanbhai', NULL, '23BIT209@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT210', 'Aayush Khandelwal', NULL, '23BIT210@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT211', 'Krishna Kishor Parmar', NULL, '23BIT211@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT212', 'Kathan Jigarkumar Mehta', NULL, '23BIT212@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT213', 'Arya Hiren Kumar Upadhyay', NULL, '23BIT213@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT214', 'Ashraf Zaz', NULL, '23BIT214@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT215', 'Vrushank Naimesh Mehra', NULL, '23BIT215@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL),
('23BIT216', 'Kanav Sandeep Patel', NULL, '23BIT216@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H5', 'Domestic', NULL);

-- Students 217-260 (Division D3_ICT, Group H6)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BIT217', 'Madhav Kishorbhai Khut', NULL, '23BIT217@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT218', 'Aditya Kiritkumar Sojitra', NULL, '23BIT218@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT219', 'Boda Karan Vijaykumar', NULL, '23BIT219@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT220', 'Tisha Viralbhai Vora', NULL, '23BIT220@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT221', 'Prachi Anish Tataria', NULL, '23BIT221@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT222', 'Mehta Aditya', NULL, '23BIT222@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT223', 'Zalak Mukeshkumar Chauhan', NULL, '23BIT223@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT224', 'Viral Ishvar Vaghela', NULL, '23BIT224@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT225', 'Manvee Choudhary', NULL, '23BIT225@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT226', 'Puru Kumar', NULL, '23BIT226@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT227', 'Harshil Mukesh Talaviya', NULL, '23BIT227@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT228', 'Dhruv Prajapati', NULL, '23BIT228@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT229', 'Kathiriya Shrey Chandrakant', NULL, '23BIT229@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT230', 'Nishant Kamleshbhai Patel', NULL, '23BIT230@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT231', 'Even Jayesbhai Patel', NULL, '23BIT231@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT232', 'Kaushal Bansidhar Rathi', NULL, '23BIT232@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT233', 'Bhavya Shaileshkumar Parmar', NULL, '23BIT233@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT234', 'Mansi Dineshbhai Rupapara', NULL, '23BIT234@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT235', 'Mit Ritesh Parekh', NULL, '23BIT235@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT236', 'Darsh Ketanbhai Kalaria', NULL, '23BIT236@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT237', 'Dev Jaybhai Doshi', NULL, '23BIT237@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT238', 'Hanil Vishnubhai Patel', NULL, '23BIT238@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT239', 'Dhruv Pranavkumar Patel', NULL, '23BIT239@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT240', 'Shriya Ajay Pancholi', NULL, '23BIT240@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT241', 'Krisha Murlidhar Trivedi', NULL, '23BIT241@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT242', 'Meet Manojbhai Kagathara', NULL, '23BIT242@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT243', 'Kavya Agrawal', NULL, '23BIT243@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT244', 'Saanvi Narendra Baweja', NULL, '23BIT244@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT245', 'Panchal Shlok Rameshbhai', NULL, '23BIT245@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT246', 'Akshat Sunil Patil', NULL, '23BIT246@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT247', 'Hetvi Shah', NULL, '23BIT247@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT248', 'Prajapati Anuj Harshadkumar', NULL, '23BIT248@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT249', 'Monish Kacha', NULL, '23BIT249@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT250', 'Suthar Aagnya Rakeshbhai', NULL, '23BIT250@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT251', 'Krish Patel', NULL, '23BIT251@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT252', 'Patel Vrutiben Sanjaybhai', NULL, '23BIT252@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT253', 'Pratham Agrawal', NULL, '23BIT253@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT254', 'Vasudev Rajendranhai Baldaniya', NULL, '23BIT254@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT255', 'Divyesh Hiteshbhai Moraniya', NULL, '23BIT255@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT256', 'Nikhil Sanjaybhai Vasoya', NULL, '23BIT256@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT257', 'Yashvi Prabhubhai Bhoye', NULL, '23BIT257@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT258', 'Prachi Anil Mishra', NULL, '23BIT258@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('23BIT259', 'Joshi Riya Bhavikbhai', NULL, '23BIT259@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL),
('21BIT092', 'Patel Abhishek Shrirambhai', NULL, '21BIT092@pdpu.ac.in', 'ICT', 'SoT', 'BTECH_ICT', 'D3_ICT', 'H6', 'Domestic', NULL);