-- Assumed Values:
-- DEPT_CODE: 'ECE'
-- SCHOOL_ID: 'SoT'
-- PROGRAM_ID: 'BTECH_ECE'
-- CONTACT_NO: NULL
-- STUDENT_TYPE: 'Domestic' -- Assuming default, adjust for specific cases like Eunike/Nangombe if known
-- IMAGE_PATH: NULL
-- EMAIL: [Final Roll No.]@pdpu.ac.in
-- DIVISION_ID Mapping: 'Div-1' -> 'D1_ECE', 'Div-2' -> 'D2_ECE', 'Div-3' -> 'D3_ECE'
-- GROUP_ID Mapping: 'F1'/'F2'/'F3'/'F4'/'F5'/'F6' directly from PDF

-- Students 1-35 (Division D1_ECE, Group F1)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC001', 'Shashank Saha', NULL, '23BEC001@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC002', 'Vidhi Rajendrasinh Padhiar', NULL, '23BEC002@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC003', 'Shreyansh Chauhan', NULL, '23BEC003@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC004', 'Shaiv Kavachkumar Amitkumar', NULL, '23BEC004@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC005', 'Samriddhi Saxena', NULL, '23BEC005@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC006', 'Dhruv Patel', NULL, '23BEC006@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC007', 'Aryan Ajay Nema', NULL, '23BEC007@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC008', 'Anurag Vijaykumar Tripathi', NULL, '23BEC008@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC009', 'Kahaan Jasmin Padiya', NULL, '23BEC009@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC010', 'Parth Hemantkumar Pandya', NULL, '23BEC010@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC011', 'Ditanshi Hiren Desai', NULL, '23BEC011@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC012', 'Eunike Ndafapawa Shapwa', NULL, '23BEC012@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'International', NULL), -- Marked as International based on name
('23BEC013', 'Rana Siddharth', NULL, '23BEC013@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC014', 'Adwait Anant Adbe', NULL, '23BEC014@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC015', 'Dev Parmar', NULL, '23BEC015@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC016', 'Bhargav', NULL, '23BEC016@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC017', 'Avani Pradeepsingh Chauhan', NULL, '23BEC017@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC018', 'Bansari Manishbhai Patel', NULL, '23BEC018@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC019', 'Henil Raiyani', NULL, '23BEC019@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC020', 'Preet Dhirendrakumar Desai', NULL, '23BEC020@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC021', 'Yash Raval', NULL, '23BEC021@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC022', 'Kevin Sunil Shah', NULL, '23BEC022@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC023', 'Aryan Kumar', NULL, '23BEC023@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC024', 'Naman Narendra Choudhary', NULL, '23BEC024@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC025', 'Krishna Dilip Khandelwal', NULL, '23BEC025@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC026', 'Ansh Pankajkumar Chaudhary', NULL, '23BEC026@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC027', 'Divyansh Mehta', NULL, '23BEC027@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC028', 'Dhruvi Rakeshkumar Singh', NULL, '23BEC028@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC029', 'Aayushi D Goyal', NULL, '23BEC029@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC030', 'Ronak Yadav', NULL, '23BEC030@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC031', 'K Bhavana Singh', NULL, '23BEC031@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC032', 'Nidhi Makwana', NULL, '23BEC032@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC033', 'Prince Patrick Makoto', NULL, '23BEC033@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'International', NULL), -- Marked as International based on name
('23BEC034', 'Darshan Virambhai Odedara', NULL, '23BEC034@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL),
('23BEC035', 'Shubhang Paresh Gaglani', NULL, '23BEC035@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F1', 'Domestic', NULL);

-- Students 36-69 (Division D1_ECE, Group F2)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC036', 'Hitarth Unjia', NULL, '23BEC036@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC037', 'Jayesh Paresh Kumar Thakkar', NULL, '23BEC037@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC038', 'Manav Patel', NULL, '23BEC038@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC039', 'Upadhyay Kartavya', NULL, '23BEC039@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC040', 'Rohan Vasansetti', NULL, '23BEC040@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC041', 'Rudra Jayeshkumar Patel', NULL, '23BEC041@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC042', 'Yug Chaudhari', NULL, '23BEC042@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC043', 'Pearl Rasesh Vyas', NULL, '23BEC043@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC044', 'Kesha Topiwala', NULL, '23BEC044@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC045', 'Saumya Kedia', NULL, '23BEC045@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC046', 'Dhyey Daxesh Shah', NULL, '23BEC046@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC047', 'Raghu Raghunandan Arora', NULL, '23BEC047@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC048', 'Bhvya Pankaj Kumar Bansal', NULL, '23BEC048@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC049', 'Umang Pramodkumar Jha', NULL, '23BEC049@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC050', 'Deshna Jain', NULL, '23BEC050@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC051', 'Suhagiya Aryan Mukeshbhai', NULL, '23BEC051@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC052', 'Gajera Devamk Kalpeshbhai', NULL, '23BEC052@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC053', 'Harit Dhirenbhai Patel', NULL, '23BEC053@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC054', 'Vatsal Pathak', NULL, '23BEC054@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC055', 'Vraj Balmukund Soni', NULL, '23BEC055@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC056', 'Jeneel Sureshkumar Nandha', NULL, '23BEC056@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC057', 'Devanshi Manoj Agarwal', NULL, '23BEC057@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC058', 'Vedant Jain', NULL, '23BEC058@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC059', 'Saharsh Sinha', NULL, '23BEC059@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC060', 'Aryan Samirbhai Shah', NULL, '23BEC060@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC061', 'Harshit Amitkumar Kohjani', NULL, '23BEC061@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC062', 'Yash Samir Shah', NULL, '23BEC062@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC063', 'Parikshit Rajesh Bhardwaj', NULL, '23BEC063@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC064', 'Priyanshu Bharwad', NULL, '23BEC064@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC065', 'Chetas Tejas Jani', NULL, '23BEC065@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC066', 'Aloukik Aishwarya', NULL, '23BEC066@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC067', 'Dhyey Bharatbhai Hingarajiya', NULL, '23BEC067@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC068', 'Sharmishtha Devi Kola', NULL, '23BEC068@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL),
('23BEC069', 'Priyansh Samip Madhu', NULL, '23BEC069@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D1_ECE', 'F2', 'Domestic', NULL);

-- Students 70-103 (Division D2_ECE, Group F3)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC070', 'Sidharth Kumar Maheshwary', NULL, '23BEC070@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC071', 'Chavda Param Dharmesh', NULL, '23BEC071@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC072', 'Ravish Snehal Patel', NULL, '23BEC072@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC073', 'Kartik Sarswat', NULL, '23BEC073@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC074', 'Diya Pritesh Shukla', NULL, '23BEC074@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC075', 'Sojitra Parth Vrajlal', NULL, '23BEC075@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC076', 'Syamantok Saha', NULL, '23BEC076@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC077', 'Hetanshu Ashish Patel', NULL, '23BEC077@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC078', 'Dhanesha Patel', NULL, '23BEC078@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC079', 'Dhruv Kalani', NULL, '23BEC079@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC080', 'Priyanka Jagdish Punjabi', NULL, '23BEC080@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC081', 'Manan Pathak', NULL, '23BEC081@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC082', 'Dhruv Kalpeshbhai Chokshi', NULL, '23BEC082@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC083', 'Heer Alpesh Patel', NULL, '23BEC083@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC084', 'Bhavika Mahesh Vasnani', NULL, '23BEC084@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC085', 'Khanjan Gaurav Buch', NULL, '23BEC085@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC086', 'Dharaditya Singh Shaktawat', NULL, '23BEC086@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC087', 'Dhairya Tejas Safolia', NULL, '23BEC087@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC088', 'Pratyush Amit Maheshwari', NULL, '23BEC088@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC089', 'Aayush Timir Satpathi', NULL, '23BEC089@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC090', 'Yash Dobariya', NULL, '23BEC090@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC091', 'Krish Piyush Thaker', NULL, '23BEC091@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC092', 'Jay Rajeshbhai Karkar', NULL, '23BEC092@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC093', 'Harsh Apoorva Patel', NULL, '23BEC093@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC094', 'Diya Dharmesh Arvadia', NULL, '23BEC094@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC095', 'Shweta Sharma', NULL, '23BEC095@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC096', 'Hetvi Ankurkumar Patel', NULL, '23BEC096@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC097', 'Ayush Kumar Singh', NULL, '23BEC097@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC098', 'Yug Ketankumar Dhamsania', NULL, '23BEC098@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC099', 'Nidhi Shukla', NULL, '23BEC099@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC100', 'Aditya Malpani', NULL, '23BEC100@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC101', 'Ayush Singhal', NULL, '23BEC101@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC102', 'Nihari Sanjay Pandya', NULL, '23BEC102@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL),
('23BEC103', 'Krish Dashrathbhai Patel', NULL, '23BEC103@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F3', 'Domestic', NULL);

-- Students 104-137 (Division D2_ECE, Group F4)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC104', 'Avisha Himanshu Patel', NULL, '23BEC104@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC105', 'Gondaliya Dhruvi Jagdishbhai', NULL, '23BEC105@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC106', 'Yash Dasadia', NULL, '23BEC106@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC107', 'Shrey Mehta', NULL, '23BEC107@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC108', 'Patel Keyur Arvindbhai', NULL, '23BEC108@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC109', 'Himanshu Inani', NULL, '23BEC109@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC110', 'Neelansh Shukla', NULL, '23BEC110@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC111', 'Smit Shah', NULL, '23BEC111@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC112', 'Rajasingh Yuvraj Chaudhary', NULL, '23BEC112@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC113', 'Manav Salil Sheth', NULL, '23BEC113@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC114', 'Palakparmar', NULL, '23BEC114@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC115', 'Kanishka Rajput', NULL, '23BEC115@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC116', 'Krins Dharmeshbhai Italiya', NULL, '23BEC116@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC117', 'Nevil Suvagiya', NULL, '23BEC117@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC118', 'Shubhi Jain', NULL, '23BEC118@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC119', 'Keshvi Vijaybhai Moradiya', NULL, '23BEC119@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC120', 'Pranav Parmar', NULL, '23BEC120@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC121', 'Tarishi Jain', NULL, '23BEC121@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC122', 'Kshitij Gurumoorthy', NULL, '23BEC122@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC123', 'Shrey Umeshkumar Parekh', NULL, '23BEC123@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC124', 'Kalrav Nileshkumar Mistry', NULL, '23BEC124@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC125', 'Mukund Sikarwar', NULL, '23BEC125@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC126', 'Mahi Patel', NULL, '23BEC126@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC127', 'Saransh Bansal', NULL, '23BEC127@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC128', 'Parisha Mittal', NULL, '23BEC128@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC129', 'Kanan Kamlesh Bajaj', NULL, '23BEC129@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC130', 'Khush Patel', NULL, '23BEC130@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC131', 'Soham Jayemdrabhai Soni', NULL, '23BEC131@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC132', 'Aaditya Jain', NULL, '23BEC132@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC133', 'Jash Miteshbhai Patel', NULL, '23BEC133@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC134', 'Ruchi Binay Dwivedi', NULL, '23BEC134@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC135', 'Parmeet Singh Chawla', NULL, '23BEC135@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC136', 'Jatan Nilesh Ghetiya', NULL, '23BEC136@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL),
('23BEC137', 'Manav Dineshbhai Chauhan', NULL, '23BEC137@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D2_ECE', 'F4', 'Domestic', NULL);

-- Students 138-171 (Division D3_ECE, Group F5)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC138', 'Neel Manish Sukheja', NULL, '23BEC138@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC139', 'Saransh Samar', NULL, '23BEC139@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC140', 'Sharnam Samirkumar Soni', NULL, '23BEC140@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC141', 'Aryan Amarendra Tiwari', NULL, '23BEC141@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC142', 'Kashish Hemal Ramaiya', NULL, '23BEC142@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC143', 'Achyut Arvind Bhanderi', NULL, '23BEC143@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC144', 'Dhruvkumar Brijeshkumar Panchal', NULL, '23BEC144@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC145', 'Nisarg Hasit Adhvaryu', NULL, '23BEC145@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC146', 'Vyom Utpal Gandhi', NULL, '23BEC146@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC147', 'Mohammad Huda Ansari', NULL, '23BEC147@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC148', 'Kalp Brijesh Shah', NULL, '23BEC148@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC149', 'Nihar Sandipbhai Solanki', NULL, '23BEC149@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC150', 'Utkarsh Shah', NULL, '23BEC150@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC151', 'Dhruv Vipulbhai Patel', NULL, '23BEC151@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC152', 'Diya Seth', NULL, '23BEC152@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC153', 'Shivanshu Jaiswal', NULL, '23BEC153@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC154', 'Vidit Khuti', NULL, '23BEC154@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC155', 'Hitanshu Parikh', NULL, '23BEC155@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC156', 'Ruchi Beenkumar Prajapati', NULL, '23BEC156@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC157', 'Gaurav Rajesh Patel', NULL, '23BEC157@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC158', 'Modi Aayush Bhaveshkumar', NULL, '23BEC158@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC159', 'Shah Namya Harmish', NULL, '23BEC159@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC160', 'Shitanshu Singh', NULL, '23BEC160@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC161', 'Shashwat Vishal Dave', NULL, '23BEC161@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC162', 'Yashkumar Bhaveshbhai Patel', NULL, '23BEC162@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC163', 'Parth Vijay Rana', NULL, '23BEC163@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC164', 'Drasti Dharmendrakumar Patel', NULL, '23BEC164@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC165', 'Dhruvi Rohan Shah', NULL, '23BEC165@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC166', 'Pratham Parmar', NULL, '23BEC166@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC167', 'Jaival Harshendu Shelat', NULL, '23BEC167@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC168', 'Smit Patel Rajeshbhai', NULL, '23BEC168@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC169', 'Shubham Chandreshbhai Kansara', NULL, '23BEC169@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC170', 'Komudi Rathore', NULL, '23BEC170@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL),
('23BEC171', 'Darpan Pinesh Thanki', NULL, '23BEC171@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F5', 'Domestic', NULL);

-- Students 172-207 (Division D3_ECE, Group F6)
INSERT INTO STUDENT (ID, NAME, CONTACT_NO, EMAIL, DEPT_CODE, SCHOOL_ID, PROGRAM_ID, DIVISION_ID, GROUP_ID, STUDENT_TYPE, IMAGE_PATH) VALUES
('23BEC172', 'Om Bharti', NULL, '23BEC172@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC173', 'Nihar Prajapati', NULL, '23BEC173@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC174', 'Shlok Gaurang Panchal', NULL, '23BEC174@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC175', 'Dhvaniben Rasiklal Patel', NULL, '23BEC175@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC176', 'Priyanka Panda', NULL, '23BEC176@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC177', 'Ronak Kishor Lodhia', NULL, '23BEC177@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC178', 'Yajurvi Yogeshkumar Patel', NULL, '23BEC178@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC179', 'Mokshit Lattha', NULL, '23BEC179@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC180', 'Divyanshi Chaurasia', NULL, '23BEC180@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC181', 'Samridhi. Sinha', NULL, '23BEC181@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC182', 'Unnati Sanjay Chaturvedi', NULL, '23BEC182@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC183', 'Heet Sanjaybhai Donda', NULL, '23BEC183@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC184', 'Rushvi Patel', NULL, '23BEC184@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC185', 'Riya Mehta', NULL, '23BEC185@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC186', 'Aarya Goswami', NULL, '23BEC186@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC187', 'Hngu Om Bharatbhai', NULL, '23BEC187@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL), -- Name check 'Hngu'?
('23BEC188', 'Diptanshu Karkari', NULL, '23BEC188@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC189', 'Manav Prahladkumar Prajapati', NULL, '23BEC189@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC190', 'Meghan Jha', NULL, '23BEC190@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC191', 'Chirag Mishra', NULL, '23BEC191@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC192', 'Akshat Sunil Agrawal', NULL, '23BEC192@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC193', 'Yug Hiteshkumar Khambholja', NULL, '23BEC193@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC194', 'Janvi Sheth', NULL, '23BEC194@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC195', 'Aryaveer Singh', NULL, '23BEC195@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC196', 'Anupreksha Jain', NULL, '23BEC196@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC197', 'Ghelani Mitisha Lateshbhai', NULL, '23BEC197@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC198', 'Kakkad Heet Dharmeshbhai', NULL, '23BEC198@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC199', 'Nangombe Ndokosho', NULL, '23BEC199@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'International', NULL), -- Marked as International based on name
('23BEC200', 'Aditya Dineshbhai Ahir', NULL, '23BEC200@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC201', 'Nirbhay Deep Bhojani', NULL, '23BEC201@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC202', 'Nandan Savsani', NULL, '23BEC202@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC203', 'Jiya Rahul Rajgor', NULL, '23BEC203@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC204', 'Somya Goel', NULL, '23BEC204@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('23BEC205', 'Jenil Hirenbhai Patel', NULL, '23BEC205@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL),
('22BEC052', 'Tishya Naik', NULL, '22BEC052@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL), -- Older Roll No
('22BEC021', 'TANMAYEE RAPURI', NULL, '22BEC021@pdpu.ac.in', 'ECE', 'SoT', 'BTECH_ECE', 'D3_ECE', 'F6', 'Domestic', NULL); -- Older Roll No